### ISSUE TITLE
如何运行项目

### ISSUE THREAD

**Issue by iDestin** [DataXujing/YOLO-V3-Tensorflow#1]
请问一下这个项目clone之后我该如何把它跑起来呢？

**Comment by DataXujing** [comment]
按照readme的步骤，下载安全帽数据或者你自己的数据集就可以跑起来了，注意要有一块显卡，才可以。

**Comment by iDestin** [comment]
> 按照readme的步骤，下载安全帽数据或者你自己的数据集就可以跑起来了，注意要有一块显卡，才可以。

感谢！笔记本的独立显卡应该可以试试

**Comment by zacwan** [comment]
你好，我有三个问题：1，data_pro里面的‘# 这部分休要修改’具体应该怎么修改呢
                                     2，我按照readme做到了第4步CUDA_VISIBLE_DEVICES=GPU_ID python train.py，不知道这一段怎么运行（在此之前我修改了args中的batch_size 为4（我的显卡显存）这样是否合理？）
                                     3，同样是第四步我直接运行了train.py,报错AttributeError: 'NoneType' object has no attribute 'shape'. debug在train_dataset = train_dataset.map这个方法运行之后. train_dataset 里面各项参数为unknown. 我应该怎么办

**Comment by DataXujing** [comment]
datapro.py是数据预处理的脚本，这个根据你自己的数据自己去参考修改，没有统一的改法，train.py中的训练参数建议先弄清楚，再修改去训练，第三个错误是你图像的路径不对，训练时根本没有读入图像，原因可能是路径问题比如路径不对，或路经中有中文行为opencv不做修改是不支持中文路径的，还有一种可能是你图像有损坏的。 建议弄请出整个流程再去训练，否则过程中出了问题不知道怎么去调整------------------ 原始邮件 ------------------
发件人: "zacwan"<notifications@github.com>
发送时间: 2020年3月2日(星期一) 凌晨0:14
收件人: "DataXujing/YOLO-V3-Tensorflow"<YOLO-V3-Tensorflow@noreply.github.com>;
抄送: "徐静"<274762204@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [DataXujing/YOLO-V3-Tensorflow] 运行 (#1)



你好，我有三个问题：1，data_pro里面的‘# 这部分休要修改’具体应该怎么修改呢
 2，我按照readme做到了第4步CUDA_VISIBLE_DEVICES=GPU_ID python train.py，不知道这一段怎么运行（在此之前我修改了args中的batch_size 为4（我的显卡显存）这样是否合理？）
 3，同样是第四步我直接运行了train.py,报错AttributeError: 'NoneType' object has no attribute 'shape'. debug在train_dataset = train_dataset.map这个方法运行之后. train_dataset 里面各项参数为unknown. 我应该怎么办
 
&mdash;

**Comment by zacwan** [comment]
非常感谢，应该是数据库文件损坏，我重新下载了，问题解决Sent from my Huawei phone-------- Original message --------From: 徐静 <notifications@github.com>Date: Sun, 1 Mar 2020, 16:41To: DataXujing/YOLO-V3-Tensorflow <YOLO-V3-Tensorflow@noreply.github.com>Cc: zacwan <jiahaowan1996@gmail.com>, Comment <comment@noreply.github.com>Subject: Re: [DataXujing/YOLO-V3-Tensorflow] 运行 (#1)datapro.py是数据预处理的脚本，这个根据你自己的数据自己去参考修改，没有统一的改法，train.py中的训练参数建议先弄清楚，再修改去训练，第三个错误是你图像的路径不对，训练时根本没有读入图像，原因可能是路径问题比如路径不对，或路经中有中文行为opencv不做修改是不支持中文路径的，还有一种可能是你图像有损坏的。 建议弄请出整个流程再去训练，否则过程中出了问题不知道怎么去调整------------------ 原始邮件 ------------------

发件人: "zacwan"<notifications@github.com>

发送时间: 2020年3月2日(星期一) 凌晨0:14

收件人: "DataXujing/YOLO-V3-Tensorflow"<YOLO-V3-Tensorflow@noreply.github.com>;

抄送: "徐静"<274762204@qq.com>;"State change"<state_change@noreply.github.com>;

主题: Re: [DataXujing/YOLO-V3-Tensorflow] 运行 (#1)







你好，我有三个问题：1，data_pro里面的‘# 这部分休要修改’具体应该怎么修改呢

 2，我按照readme做到了第4步CUDA_VISIBLE_DEVICES=GPU_ID python train.py，不知道这一段怎么运行（在此之前我修改了args中的batch_size 为4（我的显卡显存）这样是否合理？）

 3，同样是第四步我直接运行了train.py,报错AttributeError: 'NoneType' object has no attribute 'shape'. debug在train_dataset = train_dataset.map这个方法运行之后. train_dataset 里面各项参数为unknown. 我应该怎么办

 

&mdash;

**Comment by zacwan** [comment]
你好作者，我打算运行你的pretrain模型，我下载了第六步的source code和yolo_hat, 在按照readme的1-3执行。我用terminal执行了test_single_image.py但是没有任何输出，没有弹窗也没有报错。
问题：
1，test_single_image这个方法执行后如何看到结果（是不是应该有弹窗而我这次运行的有问题）？
2，这个yolo_hat中点的文件应该拷贝到哪个路径中？

**Comment by DataXujing** [comment]
1.`test_single_image.py`运行是没有弹窗的，识别记过保存在了当前路径下的detection_result.jpg文件，这里要提醒你的是我预训练的模型用的是coco的anchor而非聚类的anchor,如果运行pre_train的模型，请改为coco的anchor

2. 路径问题可以自己修改

**Comment by zacwan** [comment]
感谢作者回复，关于运行train_single_image.py,我还是有三个疑问：
1、不是很理解你所提到的pre_train模型（应该是第五步链接中的source code.zip吗）
2、你所提到的coco anchor是指676,197, 763,250, 684,283, 868,231, 745,273, 544,391, 829,258, 678,316, 713,355还是指另外一个？
3、在第五步中下载的yolo_v3_hat中的文件应该放在什么路径下（抱歉，还是有点不理解这个文件的用途）？
谢谢~

**Comment by DataXujing** [comment]
建议先好好看看代码，再去做，感觉你没有看代码就去跑了



---原始邮件---
发件人: "zacwan"<notifications@github.com&gt;
发送时间: 2020年3月8日(周日) 凌晨5:29
收件人: "DataXujing/YOLO-V3-Tensorflow"<YOLO-V3-Tensorflow@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"徐静"<274762204@qq.com&gt;;
主题: Re: [DataXujing/YOLO-V3-Tensorflow] 运行 (#1)



感谢作者回复，关于运行train_single_image.py,我还是有三个疑问：
 1、不是很理解你所提到的pre_train模型（应该是第五步链接中的source code.zip吗）
 2、你所提到的coco anchor是指676,197, 763,250, 684,283, 868,231, 745,273, 544,391, 829,258, 678,316, 713,355还是指另外一个？
 3、在第五步中下载的yolo_v3_hat中的文件应该放在什么路径下（抱歉，还是有点不理解这个文件的用途）？
 谢谢~
