### ISSUE TITLE
demo 测试问题

### ISSUE THREAD

**Issue by TianshengSun** [DataXujing/YOLO-V3-Tensorflow#2]
请问我在5中的模型应该和5中的程序一起用吗  为什么5中的程序转换的是yolo3官网的模型 并且会有不匹配的错误提示，而且使用5中的模型和code中给出的程序进行测试的话不能框出物体？

**Comment by lostemples** [comment]
同样的问题，按照ReadME里面的方法，准备了Safety-Helmet-Wearing-Dataset，自己训练， [arg里面参数都没有修改，训练loss在6左右徘徊，测试效果较差。
下载作者yolov3_hat的模型，test之后发现boxes_都非常小。

**Comment by DataXujing** [comment]
> @Huntersts 

我们检查了GitHub上的版本，提交的代码存在问题给大家带来不便，目前已经更新最新版代码，可以正常使用和测试！

**Comment by DataXujing** [comment]
> @lostemples 

训练过程loss一直不下降。可以替换优化器，在损失函数的定义中可以更改bounding box的回归损失和预测的分类损失的权重值。这要会解决您的问题，此外，代码已经更新，之前代码提交的版本有问题，可以正常测试和训练！

**Comment by DataXujing** [comment]
这个问题是我预训练的模型使用的是COCO数据集的anchor, 请使用coco数据集的anchor测试预训练的模型
