### ISSUE TITLE
使用模型进行测试的时候，出现了一些问题

### ISSUE THREAD

**Issue by one-jerry** [DataXujing/YOLO-V3-Tensorflow#3]
博主，您好：
      我在根据您的方法在使用模型的时候出现了这个问题：
Errors may have originated from an input operation.
Input Source operations connected to node save/Assign_349:
 yolov3/yolov3_head/Conv_6/biases (defined at F:\yolo3 test\YOLO-V3-Tensorflow-model\model.py:57)
导致不能运用模型进行检测。能否请教博主，这个问题如何解决。非常感谢！

**Comment by DataXujing** [comment]
注意查看 `test_single_image.py`命令行参数传入的值是否正确，比如“模型名称“

**Comment by lizhiwei98** [comment]
您好，是不是下载那个预训练模型，就可以直接识别图片了
