### ISSUE TITLE
你好，我想下载你的预训练模型yolov3_hat.rar，但是文件太大下载失败

### ISSUE THREAD

**Issue by Anyyyyyyy** [DataXujing/YOLO-V3-Tensorflow#4]
请问您可以发一份给我邮箱吗，还有那个pre_train.rar，我的邮箱是935988943@qq.com，谢谢你

**Comment by DataXujing** [comment]
因为文件过大，邮箱同样较慢，建议通过GitHub下载，耐心等待

**Comment by lizhiwei98** [comment]
不知道为什么每次下载到260m左右就下载不动了
